import { StrategyPaletteItem } from "@/types/strategy-builder";

export const STRATEGY_PALETTE_ITEMS: StrategyPaletteItem[] = [
  // --- MARKET ---
  {
    id: "price_close",
    label: "Close Price",
    category: "MARKET",
    defaultLeft: "close",
    defaultOp: ">",
    defaultRight: "ema_200",
    defaultTimeframe: "15m",
    tooltip: "Current candle closing price compared against reference",
    badge: "Price",
  },
  {
    id: "price_vwap",
    label: "VWAP",
    category: "MARKET",
    defaultLeft: "close",
    defaultOp: ">",
    defaultRight: "vwap",
    defaultTimeframe: "15m",
    tooltip: "Volume Weighted Average Price intra-day benchmark",
    badge: "VWAP",
  },
  {
    id: "pivot_p",
    label: "Daily Pivot (P)",
    category: "MARKET",
    defaultLeft: "close",
    defaultOp: ">",
    defaultRight: "pivot_p",
    defaultTimeframe: "1d",
    tooltip: "Central pivot point derived from previous day OHLC",
    badge: "Pivot",
  },
  {
    id: "fib_618",
    label: "Fibonacci 61.8% Retracement",
    category: "MARKET",
    defaultLeft: "close",
    defaultOp: ">=",
    defaultRight: "fib_618",
    defaultTimeframe: "1h",
    tooltip: "Golden ratio pullback support/resistance level",
    badge: "Fib",
  },

  // --- TREND ---
  {
    id: "ema_9_21",
    label: "EMA 9 / 21 Crossover",
    category: "TREND",
    defaultLeft: "ema_9",
    defaultOp: "crosses_above",
    defaultRight: "ema_21",
    defaultTimeframe: "15m",
    tooltip: "Fast momentum trend trigger on EMA 9 crossing EMA 21",
    badge: "Cross",
  },
  {
    id: "ema_200_trend",
    label: "EMA 200 Baseline",
    category: "TREND",
    defaultLeft: "close",
    defaultOp: ">",
    defaultRight: "ema_200",
    defaultTimeframe: "1h",
    tooltip: "Major macro regime filter (Price above EMA 200 is Bullish)",
    badge: "Macro",
  },
  {
    id: "adx_trend_strength",
    label: "ADX Trend Strength (> 25)",
    category: "TREND",
    defaultLeft: "adx",
    defaultOp: ">",
    defaultRight: "25",
    defaultTimeframe: "1h",
    tooltip: "Ensures market is strongly trending rather than choppy",
    badge: "Strength",
  },
  {
    id: "supertrend_signal",
    label: "Supertrend Direction",
    category: "TREND",
    defaultLeft: "close",
    defaultOp: ">",
    defaultRight: "supertrend",
    defaultTimeframe: "15m",
    tooltip: "ATR-based dynamic trend-following boundary",
    badge: "Trend",
  },
  {
    id: "sma_50_200_golden",
    label: "Golden Cross (SMA 50 > 200)",
    category: "TREND",
    defaultLeft: "sma_50",
    defaultOp: "crosses_above",
    defaultRight: "sma_200",
    defaultTimeframe: "1d",
    tooltip: "Classic institutional macro trend reversal signal",
    badge: "Macro",
  },

  // --- MOMENTUM ---
  {
    id: "rsi_oversold",
    label: "RSI Oversold (< 30)",
    category: "MOMENTUM",
    defaultLeft: "rsi_14",
    defaultOp: "<",
    defaultRight: "30",
    defaultTimeframe: "15m",
    tooltip: "Relative Strength Index entering deep oversold territory",
    badge: "RSI",
  },
  {
    id: "rsi_bullish_momentum",
    label: "RSI Bullish (> 50)",
    category: "MOMENTUM",
    defaultLeft: "rsi_14",
    defaultOp: ">",
    defaultRight: "50",
    defaultTimeframe: "15m",
    tooltip: "RSI in bullish momentum half",
    badge: "RSI",
  },
  {
    id: "macd_bullish_cross",
    label: "MACD Line > Signal",
    category: "MOMENTUM",
    defaultLeft: "macd_line",
    defaultOp: ">",
    defaultRight: "macd_signal",
    defaultTimeframe: "15m",
    tooltip: "MACD line crossing above signal line",
    badge: "MACD",
  },
  {
    id: "macd_hist_positive",
    label: "MACD Histogram > 0",
    category: "MOMENTUM",
    defaultLeft: "macd_hist",
    defaultOp: ">",
    defaultRight: "0",
    defaultTimeframe: "15m",
    tooltip: "Accelerating upward momentum",
    badge: "MACD",
  },
  {
    id: "stoch_oversold",
    label: "Stochastic %K (< 20)",
    category: "MOMENTUM",
    defaultLeft: "stoch_k",
    defaultOp: "<",
    defaultRight: "20",
    defaultTimeframe: "5m",
    tooltip: "Fast oscillator oversold bounce candidate",
    badge: "Stoch",
  },

  // --- VOLATILITY ---
  {
    id: "bb_lower_bounce",
    label: "Bollinger Lower Band Rebound",
    category: "VOLATILITY",
    defaultLeft: "close",
    defaultOp: "<=",
    defaultRight: "bb_lower",
    defaultTimeframe: "15m",
    tooltip: "Mean-reversion bounce opportunity from 2 standard deviation low",
    badge: "BB",
  },
  {
    id: "bb_upper_breakout",
    label: "Bollinger Upper Band Breakout",
    category: "VOLATILITY",
    defaultLeft: "close",
    defaultOp: ">=",
    defaultRight: "bb_upper",
    defaultTimeframe: "15m",
    tooltip: "High-volatility expansion breakout above band",
    badge: "BB",
  },
  {
    id: "atr_expansion",
    label: "ATR Volatility Expansion",
    category: "VOLATILITY",
    defaultLeft: "atr_14",
    defaultOp: ">",
    defaultRight: "atr_14_ma",
    defaultTimeframe: "1h",
    tooltip: "Average True Range expanding above its 20-period moving average",
    badge: "ATR",
  },

  // --- VOLUME ---
  {
    id: "volume_surge",
    label: "Volume > 1.5x 20-SMA",
    category: "VOLUME",
    defaultLeft: "volume",
    defaultOp: ">",
    defaultRight: "volume_sma_20",
    defaultTimeframe: "15m",
    tooltip: "High volume confirmation supporting price expansion",
    badge: "Vol",
  },
  {
    id: "vp_poc_support",
    label: "Volume Profile POC Support",
    category: "VOLUME",
    defaultLeft: "close",
    defaultOp: ">=",
    defaultRight: "vp_poc",
    defaultTimeframe: "1h",
    tooltip: "Point of Control highest traded volume node acting as magnet/support",
    badge: "VP",
  },
  {
    id: "vp_vah_breakout",
    label: "Value Area High Breakout (VAH)",
    category: "VOLUME",
    defaultLeft: "close",
    defaultOp: ">",
    defaultRight: "vp_vah",
    defaultTimeframe: "1h",
    tooltip: "Price breaking above upper 70% value area boundary",
    badge: "VP",
  },

  // --- PRICE ACTION & STRUCTURE ---
  {
    id: "pa_breakout_resistance",
    label: "Resistance Breakout (20-High)",
    category: "PRICE ACTION",
    defaultLeft: "close",
    defaultOp: ">",
    defaultRight: "high_20",
    defaultTimeframe: "15m",
    tooltip: "Price breaking above 20-period rolling high",
    badge: "Breakout",
  },
  {
    id: "pa_higher_high",
    label: "Higher High & Higher Low",
    category: "PRICE ACTION",
    defaultLeft: "high",
    defaultOp: ">",
    defaultRight: "prev_high",
    defaultTimeframe: "15m",
    tooltip: "Structural bullish market progression",
    badge: "Structure",
  },
  {
    id: "pa_order_block",
    label: "Bullish Order Block Support",
    category: "MARKET STRUCTURE",
    defaultLeft: "low",
    defaultOp: "<=",
    defaultRight: "order_block_top",
    defaultTimeframe: "1h",
    tooltip: "Institutional liquidity accumulation zone",
    badge: "SMC",
  },
  {
    id: "pa_fvg_fill",
    label: "Fair Value Gap (FVG) Tap",
    category: "MARKET STRUCTURE",
    defaultLeft: "low",
    defaultOp: "<=",
    defaultRight: "fvg_high",
    defaultTimeframe: "15m",
    tooltip: "Imbalance mitigation entry zone",
    badge: "FVG",
  },

  // --- OPTIONS ---
  {
    id: "opt_pcr_bullish",
    label: "Put-Call Ratio (PCR > 1.2)",
    category: "OPTIONS",
    defaultLeft: "pcr",
    defaultOp: ">",
    defaultRight: "1.2",
    defaultTimeframe: "1d",
    tooltip: "High Put volume/OI indicating oversold contrarian bullish sentiment",
    badge: "Options",
  },
  {
    id: "opt_iv_percentile",
    label: "Implied Volatility Rank (> 60%)",
    category: "OPTIONS",
    defaultLeft: "iv_rank",
    defaultOp: ">",
    defaultRight: "60",
    defaultTimeframe: "1d",
    tooltip: "High IV environment ideal for option selling / credit spreads",
    badge: "IV",
  },
  {
    id: "opt_delta_sweetspot",
    label: "Delta Strike (0.30 - 0.50)",
    category: "OPTIONS",
    defaultLeft: "delta",
    defaultOp: ">=",
    defaultRight: "0.30",
    defaultTimeframe: "1d",
    tooltip: "Optimal risk-reward directional option delta",
    badge: "Greeks",
  },
  {
    id: "opt_max_pain_gravity",
    label: "Spot Approaching Max Pain",
    category: "OPTIONS",
    defaultLeft: "close",
    defaultOp: "crosses_above",
    defaultRight: "max_pain",
    defaultTimeframe: "1d",
    tooltip: "Expiration pin gravity level",
    badge: "Options",
  },

  // --- FUTURES ---
  {
    id: "fut_funding_rate_negative",
    label: "Funding Rate Negative (Short Squeeze)",
    category: "FUTURES",
    defaultLeft: "funding_rate_pct",
    defaultOp: "<",
    defaultRight: "-0.01",
    defaultTimeframe: "4h",
    tooltip: "Crowded short market creating squeeze conditions",
    badge: "Futures",
  },
  {
    id: "fut_oi_surge",
    label: "Futures OI Expansion (+5%)",
    category: "FUTURES",
    defaultLeft: "oi_change_pct",
    defaultOp: ">",
    defaultRight: "5.0",
    defaultTimeframe: "1h",
    tooltip: "Fresh capital entering futures contracts",
    badge: "OI",
  },
  {
    id: "fut_basis_contango",
    label: "Positive Annualized Basis (> 8%)",
    category: "FUTURES",
    defaultLeft: "basis_pct",
    defaultOp: ">",
    defaultRight: "8.0",
    defaultTimeframe: "1d",
    tooltip: "Healthy contango premium indicating sustained spot demand",
    badge: "Basis",
  },

  // --- RISK ---
  {
    id: "risk_atr_stop_15",
    label: "Dynamic 1.5 ATR Stop Loss",
    category: "RISK",
    defaultLeft: "stop_loss",
    defaultOp: "==",
    defaultRight: "1.5 * atr_14",
    defaultTimeframe: "15m",
    tooltip: "Volatility-adapted stop distance protecting against noise",
    badge: "SL",
  },
  {
    id: "risk_reward_20",
    label: "2.0x Risk-Reward Take Profit",
    category: "RISK",
    defaultLeft: "take_profit",
    defaultOp: "==",
    defaultRight: "2.0 * stop_distance",
    defaultTimeframe: "15m",
    tooltip: "Mathematical expectancy positive target",
    badge: "TP",
  },
];
