import { StrategyPaletteItem } from "@/types/strategy-builder";

export const STRATEGY_PALETTE_ITEMS: StrategyPaletteItem[] = [
  // --- MARKET & PRICE ---
  {
    id: "price_close",
    label: "Close Price",
    category: "MARKET",
    defaultLeft: "close",
    defaultOp: ">",
    defaultRight: "ema_200",
    defaultTimeframe: "15m",
    tooltip: "Current candle closing price compared against reference or indicator",
    badge: "Price",
  },
  {
    id: "price_vwap",
    label: "VWAP",
    category: "MARKET",
    defaultLeft: "close",
    defaultOp: ">",
    defaultRight: "vwap",
    defaultTimeframe: "15m",
    tooltip: "Volume Weighted Average Price intra-day benchmark",
    badge: "VWAP",
  },
  {
    id: "pivot_p",
    label: "Daily Pivot (P)",
    category: "MARKET",
    defaultLeft: "close",
    defaultOp: ">",
    defaultRight: "pivot_p",
    defaultTimeframe: "1d",
    tooltip: "Central pivot point derived from previous day OHLC",
    badge: "Pivot",
  },
  {
    id: "fib_618",
    label: "Fibonacci 61.8% Retracement",
    category: "MARKET",
    defaultLeft: "close",
    defaultOp: ">=",
    defaultRight: "fib_618",
    defaultTimeframe: "1h",
    tooltip: "Golden ratio pullback support/resistance level",
    badge: "Fib",
  },

  // --- TREND ---
  {
    id: "ema_9_21",
    label: "EMA 9 / 21 Crossover",
    category: "TREND",
    defaultLeft: "ema_9",
    defaultOp: "crosses_above",
    defaultRight: "ema_21",
    defaultTimeframe: "15m",
    tooltip: "Fast momentum trend trigger on EMA 9 crossing EMA 21",
    badge: "Cross",
  },
  {
    id: "ema_50",
    label: "EMA 50 Trend Filter",
    category: "TREND",
    defaultLeft: "close",
    defaultOp: ">",
    defaultRight: "ema_50",
    defaultTimeframe: "15m",
    tooltip: "Medium-term intermediate trend support filter",
    badge: "Trend",
  },
  {
    id: "ema_200_trend",
    label: "EMA 200 Baseline",
    category: "TREND",
    defaultLeft: "close",
    defaultOp: ">",
    defaultRight: "ema_200",
    defaultTimeframe: "1h",
    tooltip: "Major macro regime filter (Price above EMA 200 is Bullish)",
    badge: "Macro",
  },
  {
    id: "sma_200_bench",
    label: "SMA 200 Benchmark",
    category: "TREND",
    defaultLeft: "close",
    defaultOp: ">",
    defaultRight: "sma_200",
    defaultTimeframe: "1d",
    tooltip: "Classic institutional simple moving average benchmark",
    badge: "SMA",
  },
  {
    id: "adx_trend_strength",
    label: "ADX Trend Strength (> 25)",
    category: "TREND",
    defaultLeft: "adx",
    defaultOp: ">",
    defaultRight: "25",
    defaultTimeframe: "1h",
    tooltip: "Ensures market is strongly trending rather than choppy",
    badge: "Strength",
  },
  {
    id: "supertrend_signal",
    label: "Supertrend Direction",
    category: "TREND",
    defaultLeft: "close",
    defaultOp: ">",
    defaultRight: "supertrend",
    defaultTimeframe: "15m",
    tooltip: "ATR-based dynamic trend-following boundary",
    badge: "Trend",
  },
  {
    id: "sma_50_200_golden",
    label: "Golden Cross (SMA 50 > 200)",
    category: "TREND",
    defaultLeft: "sma_50",
    defaultOp: "crosses_above",
    defaultRight: "sma_200",
    defaultTimeframe: "1d",
    tooltip: "Macro golden cross / death cross trend signal",
    badge: "Golden",
  },
  {
    id: "parabolic_sar",
    label: "Parabolic SAR",
    category: "TREND",
    defaultLeft: "close",
    defaultOp: ">",
    defaultRight: "psar",
    defaultTimeframe: "15m",
    tooltip: "Stop and Reverse trailing trend tracking system",
    badge: "PSAR",
  },

  // --- MOMENTUM ---
  {
    id: "rsi_oversold_30",
    label: "RSI Reversal (< 30)",
    category: "MOMENTUM",
    defaultLeft: "rsi_14",
    defaultOp: "<",
    defaultRight: "30",
    defaultTimeframe: "15m",
    tooltip: "Relative Strength Index entering deep oversold territory",
    badge: "Oversold",
  },
  {
    id: "rsi_bullish_55",
    label: "RSI Bullish Momentum (> 55)",
    category: "MOMENTUM",
    defaultLeft: "rsi_14",
    defaultOp: ">",
    defaultRight: "55",
    defaultTimeframe: "15m",
    tooltip: "RSI confirming strong bullish continuation momentum",
    badge: "Momentum",
  },
  {
    id: "macd_bullish_cross",
    label: "MACD Signal Line Cross",
    category: "MOMENTUM",
    defaultLeft: "macd_line",
    defaultOp: "crosses_above",
    defaultRight: "macd_signal",
    defaultTimeframe: "15m",
    tooltip: "MACD fast line crossing above the 9-period signal line",
    badge: "MACD",
  },
  {
    id: "macd_hist_positive",
    label: "MACD Histogram > 0",
    category: "MOMENTUM",
    defaultLeft: "macd_hist",
    defaultOp: ">",
    defaultRight: "0",
    defaultTimeframe: "15m",
    tooltip: "MACD momentum expansion above the zero baseline",
    badge: "Hist",
  },
  {
    id: "stoch_oversold",
    label: "Stochastic %K / %D Cross",
    category: "MOMENTUM",
    defaultLeft: "stoch_k",
    defaultOp: "crosses_above",
    defaultRight: "stoch_d",
    defaultTimeframe: "15m",
    tooltip: "Stochastic oscillator momentum alignment trigger",
    badge: "Stoch",
  },
  {
    id: "cci_breakout",
    label: "CCI Breakout (> 100)",
    category: "MOMENTUM",
    defaultLeft: "cci_20",
    defaultOp: ">",
    defaultRight: "100",
    defaultTimeframe: "15m",
    tooltip: "Commodity Channel Index cyclical trend breakout",
    badge: "CCI",
  },
  {
    id: "roc_velocity",
    label: "Rate of Change (ROC > 0)",
    category: "MOMENTUM",
    defaultLeft: "roc_12",
    defaultOp: ">",
    defaultRight: "0",
    defaultTimeframe: "15m",
    tooltip: "Price velocity and percentage rate of change",
    badge: "ROC",
  },

  // --- VOLATILITY ---
  {
    id: "bb_lower_bounce",
    label: "Bollinger Lower Band Bounce",
    category: "VOLATILITY",
    defaultLeft: "close",
    defaultOp: "<=",
    defaultRight: "bb_lower_20_2",
    defaultTimeframe: "15m",
    tooltip: "Price tagging or piercing the 2-standard-deviation lower band",
    badge: "Bands",
  },
  {
    id: "bb_squeeze",
    label: "Bollinger Band Squeeze (< 0.04)",
    category: "VOLATILITY",
    defaultLeft: "bb_bandwidth",
    defaultOp: "<",
    defaultRight: "0.04",
    defaultTimeframe: "1h",
    tooltip: "Volatility contraction indicating impending explosive breakout",
    badge: "Squeeze",
  },
  {
    id: "atr_expansion",
    label: "ATR Volatility Expansion",
    category: "VOLATILITY",
    defaultLeft: "atr_14",
    defaultOp: ">",
    defaultRight: "atr_sma_20",
    defaultTimeframe: "15m",
    tooltip: "Current ATR expanding above its 20-period moving average",
    badge: "ATR",
  },
  {
    id: "iv_rank_high",
    label: "IV Rank (> 50)",
    category: "VOLATILITY",
    defaultLeft: "iv_rank",
    defaultOp: ">",
    defaultRight: "50",
    defaultTimeframe: "1d",
    tooltip: "Implied Volatility Rank in upper half of annual range",
    badge: "IV Rank",
  },
  {
    id: "iv_percentile_low",
    label: "IV Percentile (< 25)",
    category: "VOLATILITY",
    defaultLeft: "iv_percentile",
    defaultOp: "<",
    defaultRight: "25",
    defaultTimeframe: "1d",
    tooltip: "Cheap option premium conditions favorable for debit buying",
    badge: "IV %ile",
  },

  // --- VOLUME & LIQUIDITY ---
  {
    id: "vol_surge_2x",
    label: "Volume Surge (2x 20-SMA)",
    category: "VOLUME",
    defaultLeft: "volume",
    defaultOp: ">",
    defaultRight: "volume_sma_20 * 2",
    defaultTimeframe: "15m",
    tooltip: "High-conviction institutional participation surge",
    badge: "Surge",
  },
  {
    id: "obv_trend",
    label: "OBV Bullish Trend",
    category: "VOLUME",
    defaultLeft: "obv",
    defaultOp: ">",
    defaultRight: "obv_ema_20",
    defaultTimeframe: "1h",
    tooltip: "On-Balance Volume confirming accumulation and buying pressure",
    badge: "OBV",
  },
  {
    id: "frvp_poc_retrace",
    label: "FRVP Point of Control (POC)",
    category: "VOLUME",
    defaultLeft: "close",
    defaultOp: "==",
    defaultRight: "poc_level",
    defaultTimeframe: "15m",
    tooltip: "Price testing the highest traded volume level in fixed range",
    badge: "POC",
  },
  {
    id: "mfi_oversold",
    label: "Money Flow Index (< 20)",
    category: "VOLUME",
    defaultLeft: "mfi_14",
    defaultOp: "<",
    defaultRight: "20",
    defaultTimeframe: "15m",
    tooltip: "Volume-weighted RSI showing institutional capitulation",
    badge: "MFI",
  },

  // --- DERIVATIVES, OPTIONS & GREEKS ---
  {
    id: "oi_rising",
    label: "Open Interest Rising (+5%)",
    category: "DERIVATIVES",
    defaultLeft: "oi_change_pct",
    defaultOp: ">",
    defaultRight: "5.0",
    defaultTimeframe: "15m",
    tooltip: "Fresh capital entering the market confirming trend conviction",
    badge: "OI Rise",
  },
  {
    id: "pcr_bullish",
    label: "Put-Call Ratio (> 1.2)",
    category: "OPTIONS",
    defaultLeft: "pcr",
    defaultOp: ">",
    defaultRight: "1.2",
    defaultTimeframe: "15m",
    tooltip: "High Put-to-Call ratio indicating heavy put writing support",
    badge: "PCR",
  },
  {
    id: "delta_target",
    label: "Option Delta Selection (0.30 - 0.50)",
    category: "GREEKS",
    defaultLeft: "option_delta",
    defaultOp: "in_range",
    defaultRight: "0.30, 0.50",
    defaultTimeframe: "1d",
    tooltip: "Strike selection targeting optimal directional leverage",
    badge: "Delta",
  },
  {
    id: "theta_decay",
    label: "Theta Decay Favorable (> $15/day)",
    category: "GREEKS",
    defaultLeft: "option_theta",
    defaultOp: ">",
    defaultRight: "15.0",
    defaultTimeframe: "1d",
    tooltip: "Positive daily time-decay for options selling strategies",
    badge: "Theta",
  },
  {
    id: "funding_rate_low",
    label: "Crypto Funding Rate (< 0.01%)",
    category: "FUNDING",
    defaultLeft: "funding_rate",
    defaultOp: "<",
    defaultRight: "0.0001",
    defaultTimeframe: "4h",
    tooltip: "Perpetual funding rate neutral/negative favorable for long",
    badge: "Funding",
  },
  {
    id: "basis_annualized",
    label: "Futures Basis Annualized (> 5%)",
    category: "DERIVATIVES",
    defaultLeft: "basis_annualized_pct",
    defaultOp: ">",
    defaultRight: "5.0",
    defaultTimeframe: "1d",
    tooltip: "Cash & carry arbitrage basis yield spread",
    badge: "Basis",
  },

  // --- STRUCTURE & PRICE ACTION ---
  {
    id: "market_structure_hh",
    label: "Market Structure (Bullish HH/HL)",
    category: "STRUCTURE",
    defaultLeft: "market_structure",
    defaultOp: "==",
    defaultRight: "BULLISH",
    defaultTimeframe: "15m",
    tooltip: "Confirmed sequence of Higher Highs and Higher Lows",
    badge: "Structure",
  },
  {
    id: "breakout_prev_high",
    label: "20-Period High Breakout",
    category: "STRUCTURE",
    defaultLeft: "close",
    defaultOp: ">",
    defaultRight: "highest_high_20",
    defaultTimeframe: "15m",
    tooltip: "Donchian channel 20-bar resistance breakout",
    badge: "Breakout",
  },
  {
    id: "pinbar_bullish",
    label: "Bullish Pinbar / Hammer",
    category: "STRUCTURE",
    defaultLeft: "candle_pattern",
    defaultOp: "==",
    defaultRight: "BULLISH_PINBAR",
    defaultTimeframe: "15m",
    tooltip: "Long lower shadow rejection candle indicating demand",
    badge: "Candle",
  },
  {
    id: "custom_formula_expr",
    label: "Custom Math Formula",
    category: "CUSTOM",
    defaultLeft: "rsi_15m / close_15m",
    defaultOp: "<",
    defaultRight: "0.02",
    defaultTimeframe: "15m",
    tooltip: "User-defined quantitative ratio or custom rule formula",
    badge: "Custom",
  },
];
