/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./context/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./hooks/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        qos: {
          bg: "var(--qos-bg)",
          "bg-soft": "var(--qos-bg-soft)",
          sidebar: "var(--qos-sidebar)",
          header: "var(--qos-header)",
          panel: "var(--qos-panel)",
          "panel-2": "var(--qos-panel-2)",
          "panel-3": "var(--qos-panel-3)",
          "panel-soft": "var(--qos-panel-2)",
          "panel-hover": "var(--qos-panel-hover)",
          "green-panel": "var(--qos-green-panel)",
          "green-border": "var(--qos-green-border)",
          border: "var(--qos-border)",
          "border-soft": "var(--qos-border-soft)",
          "border-hover": "var(--qos-border-hover)",
          "border-active": "var(--qos-border-active)",
          primary: "var(--qos-blue)",
          "primary-hover": "var(--qos-blue-hover)",
          blue: "var(--qos-blue)",
          "blue-hover": "var(--qos-blue-hover)",
          cyan: "var(--qos-cyan)",
          "cyan-strong": "var(--qos-cyan-strong)",
          text: "var(--qos-text-primary)",
          "text-secondary": "var(--qos-text-secondary)",
          "text-muted": "var(--qos-text-muted)",
          "text-faint": "var(--qos-text-faint)",
          profit: "var(--qos-profit)",
          "profit-soft": "var(--qos-profit-soft)",
          loss: "var(--qos-loss)",
          critical: "var(--qos-critical)",
          warning: "var(--qos-warning)",
          orange: "var(--qos-orange)",
          violet: "var(--qos-violet)",
          paper: "var(--qos-paper)",
          shadow: "var(--qos-shadow)",
          "live-locked": "var(--qos-live-locked)",
          live: "var(--qos-live)",
        },
        terminal: {
          bg: "#050A12",
          surface: "#0A1422",
          elevated: "#101B2D",
          card: "#0A1422",
          border: "#1A2A3F",
          borderSubtle: "#122033",
          borderActive: "#16C6F4",
          borderHover: "#29415F",
          textPrimary: "#F7FAFC",
          textSecondary: "#B2C0D2",
          textMuted: "#7C8CA3",
          cyan: "#22D3EE",
          blue: "#2563EB",
          purple: "#7C3AED",
          green: "#00E890",
          red: "#FF3B5C",
          amber: "#F59E0B",
        },
      },
      fontSize: {
        "2xs": "var(--qos-text-2xs)",
        xs: "var(--qos-text-xs)",
        sm: "var(--qos-text-sm)",
        base: "var(--qos-text-base)",
        md: "var(--qos-text-md)",
        lg: "var(--qos-text-lg)",
        xl: "var(--qos-text-xl)",
        "2xl": "var(--qos-text-2xl)",
        "3xl": "var(--qos-text-3xl)",
      },
      fontFamily: {
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
        mono: [
          "JetBrains Mono",
          "IBM Plex Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "monospace",
        ],
      },
      letterSpacing: {
        tightest: "-0.02em",
        tighter: "-0.01em",
        normal: "0em",
        wide: "0.02em",
        wider: "0.04em",
        widest: "0.06em",
      },
      borderRadius: {
        sm: "6px",
        DEFAULT: "8px",
        md: "10px",
        lg: "12px",
        xl: "14px",
        "2xl": "16px",
      },
    },
  },
  plugins: [],
};
