/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        theme: {
          bg: "var(--theme-bg)",
          surface: "var(--theme-surface)",
          elevated: "var(--theme-elevated)",
          border: "var(--theme-border)",
          borderSubtle: "var(--theme-border-subtle)",
          textPrimary: "var(--theme-text-primary)",
          textSecondary: "var(--theme-text-secondary)",
          textMuted: "var(--theme-text-muted)",
          accent: "var(--theme-accent)",
          profit: "var(--theme-profit)",
          loss: "var(--theme-loss)",
          warning: "var(--theme-warning)",
          info: "var(--theme-info)",
          live: "var(--theme-live)",
          paper: "var(--theme-paper)",
          halted: "var(--theme-halted)",
          neutral: "var(--theme-neutral)",
        },
        // Backward-compatible mappings
        eco: {
          bg: "var(--theme-bg)",
          surface: "var(--theme-surface)",
          elevated: "var(--theme-elevated)",
          border: "var(--theme-border)",
          borderSubtle: "var(--theme-border-subtle)",
          deepForest: "var(--theme-surface)",
          forest: "var(--theme-elevated)",
          leaf: "var(--theme-accent)",
          sage: "var(--theme-accent)",
          mint: "var(--theme-profit)",
          moss: "var(--theme-text-muted)",
          text: "var(--theme-text-primary)",
          textSecondary: "var(--theme-text-secondary)",
          textMuted: "var(--theme-text-muted)",
          profit: "var(--theme-profit)",
          loss: "var(--theme-loss)",
          warning: "var(--theme-warning)",
          info: "var(--theme-info)",
          live: "var(--theme-live)",
          paper: "var(--theme-paper)",
          halted: "var(--theme-halted)",
          neutral: "var(--theme-neutral)",
        },
        obsidian: {
          950: "var(--theme-bg)",
          900: "var(--theme-surface)",
          850: "var(--theme-elevated)",
          800: "var(--theme-border)",
          750: "var(--theme-border-subtle)",
          700: "var(--theme-border)",
          600: "var(--theme-border)",
          500: "var(--theme-text-muted)",
        },
      },
      fontFamily: {
        sans: ["var(--theme-font-sans)"],
        mono: ["var(--theme-font-mono)"],
      },
      borderRadius: {
        theme: "var(--theme-radius)",
        "theme-sm": "var(--theme-radius-sm)",
        "theme-lg": "var(--theme-radius-lg)",
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "theme-glow": "themeGlow 3s ease-in-out infinite alternate",
      },
      keyframes: {
        themeGlow: {
          "0%": { boxShadow: "0 0 10px rgba(47, 208, 127, 0.2)" },
          "100%": { boxShadow: "0 0 20px rgba(47, 208, 127, 0.45)" },
        },
      },
    },
  },
  plugins: [],
};
