/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./context/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./hooks/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        terminal: {
          bg: "#030712",
          surface: "#07101F",
          elevated: "#0A1426",
          card: "#081224",
          border: "#162238",
          borderSubtle: "#0E1A2C",
          borderActive: "#00E5FF",
          borderHover: "#1F3150",
          textPrimary: "#F1F5F9",
          textSecondary: "#94A3B8",
          textMuted: "#64748B",
          cyan: "#00E5FF",
          blue: "#38BDF8",
          purple: "#8B5CF6",
          green: "#10B981",
          red: "#F43F5E",
          amber: "#F59E0B",
        },
        q: {
          bg: "var(--q-bg)",
          workspace: "var(--q-workspace)",
          surface: "var(--q-surface)",
          elevated: "var(--q-elevated)",
          card: "var(--q-card)",
          border: "var(--q-border)",
          borderHover: "var(--q-border-hover)",
          text: "var(--q-text)",
          textSecondary: "var(--q-text-secondary)",
          muted: "var(--q-muted)",
          accent: "var(--q-accent)",
          strategy: "var(--q-strategy)",
          positive: "var(--q-positive)",
          negative: "var(--q-negative)",
          warning: "var(--q-warning)",
          info: "var(--q-info)",
        },
        theme: {
          bg: "var(--theme-bg)",
          surface: "var(--theme-surface)",
          elevated: "var(--theme-elevated)",
          border: "var(--theme-border)",
          borderSubtle: "var(--theme-border-subtle)",
          textPrimary: "var(--theme-text-primary)",
          textSecondary: "var(--theme-text-secondary)",
          textMuted: "var(--theme-text-muted)",
          accent: "var(--theme-accent)",
          profit: "var(--theme-profit)",
          loss: "var(--theme-loss)",
          warning: "var(--theme-warning)",
          info: "var(--theme-info)",
          live: "var(--theme-live)",
          paper: "var(--theme-paper)",
          halted: "var(--theme-halted)",
          neutral: "var(--theme-neutral)",
        },
        // Backward-compatible mappings
        eco: {
          bg: "var(--theme-bg)",
          surface: "var(--theme-surface)",
          elevated: "var(--theme-elevated)",
          border: "var(--theme-border)",
          borderSubtle: "var(--theme-border-subtle)",
          deepForest: "var(--theme-surface)",
          forest: "var(--theme-elevated)",
          leaf: "var(--theme-accent)",
          sage: "var(--theme-accent)",
          mint: "var(--theme-profit)",
          moss: "var(--theme-text-muted)",
          text: "var(--theme-text-primary)",
          textSecondary: "var(--theme-text-secondary)",
          textMuted: "var(--theme-text-muted)",
          profit: "var(--theme-profit)",
          loss: "var(--theme-loss)",
          warning: "var(--theme-warning)",
          info: "var(--theme-info)",
          live: "var(--theme-live)",
          paper: "var(--theme-paper)",
          halted: "var(--theme-halted)",
          neutral: "var(--theme-neutral)",
        },
        obsidian: {
          950: "var(--theme-bg)",
          900: "var(--theme-surface)",
          850: "var(--theme-elevated)",
          800: "var(--theme-border)",
          750: "var(--theme-border-subtle)",
          700: "var(--theme-border)",
          600: "var(--theme-border)",
          500: "var(--theme-text-muted)",
        },
      },
      fontFamily: {
        sans: ["var(--theme-font-sans)"],
        mono: ["var(--theme-font-mono)"],
      },
      borderRadius: {
        theme: "var(--theme-radius)",
        "theme-sm": "var(--theme-radius-sm)",
        "theme-lg": "var(--theme-radius-lg)",
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "theme-glow": "themeGlow 3s ease-in-out infinite alternate",
      },
      keyframes: {
        themeGlow: {
          "0%": { boxShadow: "0 0 10px rgba(47, 208, 127, 0.2)" },
          "100%": { boxShadow: "0 0 20px rgba(47, 208, 127, 0.45)" },
        },
      },
    },
  },
  plugins: [],
};
