syntax = "proto3";

package com.upstox.marketdatafeeder.rpc.proto;

enum Type {
    initial_feed = 0;
    live_feed = 1;
}

message LTPC {
    double ltp = 1;
    int64 ltt = 2;
    int64 ltq = 3;
    double cp = 4;
}

message Quote {
    int32 bq = 1;
    double bp = 2;
    int32 bno = 3;
    int32 aq = 4;
    double ap = 5;
    int32 ano = 6;
}

message MarketLevel {
    repeated Quote bidAskQuote = 1;
}

message OHLC {
    string interval = 1;
    double open = 2;
    double high = 3;
    double low = 4;
    double close = 5;
    int64 volume = 6;
    int64 ts = 7;
}

message MarketOHLC {
    repeated OHLC ohlc = 1;
}

message OptionGreeks {
    double op = 1;
    double up = 2;
    double iv = 3;
    double delta = 4;
    double theta = 5;
    double gamma = 6;
    double vega = 7;
    double rho = 8;
}

message ExtendedFeedDetails {
    double atp = 1;
    double cp = 2;
    int64 v = 3;
    double oi = 4;
    double changeOi = 5;
    double lastClose = 6;
    int64 tbq = 7;
    int64 tsq = 8;
    double close = 9;
    double lc = 10;
    double uc = 11;
    double yh = 12;
    double yl = 13;
    double fp = 14;
    double fv = 15;
    double mbp = 16;
}

message MarketFullFeed {
    LTPC ltpc = 1;
    MarketLevel marketLevel = 2;
    OptionGreeks optionGreeks = 3;
    MarketOHLC marketOHLC = 4;
    ExtendedFeedDetails eFeedDetails = 5;
}

message IndexFullFeed {
    LTPC ltpc = 1;
    MarketOHLC marketOHLC = 2;
    ExtendedFeedDetails eFeedDetails = 3;
}

message FullFeed {
    oneof FullFeedUnion {
        MarketFullFeed marketFF = 1;
        IndexFullFeed indexFF = 2;
    }
}

message Feed {
    oneof FeedUnion {
        LTPC ltpc = 1;
        FullFeed fullFeed = 2;
    }
}

message FeedResponse {
    Type type = 1;
    map<string, Feed> feeds = 2;
    int64 currentTs = 3;
}
