import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import tests.test_upstox_5000_stocks as t1
from tests.test_angelone_zerodha_adapters import TestAngelOneAdapter, TestZerodhaAdapter, TestRegistryIntegration
import tests.test_options_data_truth_and_layout as t3

print('========================================================')
print('=== 1. UPSTOX 5,000+ INDIAN STOCKS TEST SUITE ===')
print('========================================================')
t1.test_upstox_service_master_count()
print('PASS: test_upstox_service_master_count (5280 equities loaded)')
t1.test_upstox_service_key_resolution()
print('PASS: test_upstox_service_key_resolution (Large/Mid/Small-Cap & Index keys resolved)')
t1.test_upstox_service_canonical_resolution()
print('PASS: test_upstox_service_canonical_resolution (ISIN & Key -> Canonical symbol)')
t1.test_upstox_service_search_and_pagination()
print('PASS: test_upstox_service_search_and_pagination (Search & Pagination across 5,000+)')
t1.test_symbol_master_5000_equities()
print('PASS: test_symbol_master_5000_equities (GlobalSymbolMaster 5280 equities)')
t1.test_nse_market_provider_5000_equities()
print('PASS: test_nse_market_provider_5000_equities (NSEMarketProvider 5362 instruments)')
t1.test_stock_discovery_engine_5000_stocks()
print('PASS: test_stock_discovery_engine_5000_stocks (StockDiscoveryEngine 5313 stocks)')
t1.test_canonical_instrument_resolver_dynamic()
print('PASS: test_canonical_instrument_resolver_dynamic (Dynamic resolution via Upstox)')

print('\n========================================================')
print('=== 2. ANGEL ONE & ZERODHA ADAPTER TEST SUITE ===')
print('========================================================')
a_tests = TestAngelOneAdapter()
a_tests.test_angelone_initialization_and_capability()
a_tests.test_angelone_paper_account_summary()
a_tests.test_angelone_order_management()
a_tests.test_angelone_connection_probe()
print('PASS: 4/4 Angel One tests')

z_tests = TestZerodhaAdapter()
z_tests.test_zerodha_initialization_and_capability()
z_tests.test_zerodha_login_url()
z_tests.test_zerodha_checksum_generation()
z_tests.test_zerodha_paper_account_summary()
z_tests.test_zerodha_order_management()
print('PASS: 5/5 Zerodha tests')

r_tests = TestRegistryIntegration()
r_tests.test_connection_registry_has_angel_and_zerodha()
r_tests.test_provider_service_detects_credentials()
print('PASS: 2/2 Provider Registry tests')

print('\n========================================================')
print('=== 3. OPTION CHAIN TRUTH & LAYOUT SUITE ===')
print('========================================================')
t3.test_instrument_aware_step_sizes()
t3.test_nifty_atm_calculation()
t3.test_banknifty_atm_calculation()
t3.test_strict_null_preservation_in_universe_snapshot()
t3.test_exact_single_atm_strike_tagged_in_normalized_chain()
t3.test_dhan_auth_failure_fail_closed()
print('PASS: 6/6 Option Chain truth tests')

print('\n>>> ALL 25 TESTS IN THE COMPLETE SUITE PASSED PERFECTLY! <<<')
sys.stdout.flush()
os._exit(0)
