"""
QUANT.OS AUTHORITATIVE 30 CRYPTO STRATEGIES REGISTRY
=====================================================
Authoritative Python backend definitions for all 30 crypto trading strategies.
Matches the authoritative document and frontend specifications precisely.
"""

from typing import Dict, List, Any

CRYPTO_30_STRATEGIES_BACKEND: List[Dict[str, Any]] = [
    # PART I — TREND & CONTINUATION
    {
        "strategy_id": "crypto-strat-01",
        "strategy_number": "01",
        "name": "Trend Pullback to EMA",
        "part": "PART I — TREND & CONTINUATION",
        "category": "Trend & Continuation",
        "primary_timeframe": "4H",
        "alternate_timeframes": ["1H", "1D"],
        "market": "BTC / ETH / Major liquid alts",
        "direction": "LONG / SHORT",
        "complexity": "Introductory",
        "status": "APPROVED",
        "compatible_regimes": ["TRENDING"],
        "data_requirements": ["OHLCV", "EMA (20, 50, 200)", "ATR (14)", "Volume SMA (20)"],
        "what_it_does": "The market is trending in a defined direction. Price pulls back toward the reference EMA. The strategy waits for the pullback to finish. It then enters only after the predefined continuation trigger confirms trend resumption.",
        "why_it_exists": "Trends rarely move linearly. Institutional participants utilize liquidity retracements to reference moving averages to scale into trend positions without moving order book depth aggressively.",
        "best_market_conditions": ["Sustained directional trending regimes (ADX > 25)", "Clear higher highs / higher lows (Long) or lower highs / lower lows (Short)", "Healthy volume and moderate volatility"],
        "unfavorable_conditions": ["Ranging or sideways market with ADX < 20", "Price churning flat directly across the EMA 200", "Illiquid weekend trading periods with wide bid-ask spread"],
        "default_parameters": {"ema_fast": 20, "ema_medium": 50, "ema_slow": 200, "atr_period": 14, "rr_ratio": 2.0, "max_risk_pct": 0.5},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-02",
        "strategy_number": "02",
        "name": "Momentum Expansion",
        "part": "PART I — TREND & CONTINUATION",
        "category": "Trend & Continuation",
        "primary_timeframe": "1H",
        "alternate_timeframes": ["15m", "4H"],
        "market": "BTC / ETH / liquid alts",
        "direction": "LONG / SHORT",
        "complexity": "Intermediate",
        "status": "APPROVED",
        "compatible_regimes": ["BREAKOUT / EXPANSION", "TRENDING"],
        "data_requirements": ["OHLCV", "MACD (12, 26, 9)", "RSI (14)", "Volume SMA (20)", "ATR (14)"],
        "what_it_does": "Detects early-stage momentum expansion as price accelerates out of multi-candle compression zones with surging directional volume and expanding momentum oscillators.",
        "why_it_exists": "Momentum ignition forces late market participants to chase and offside counter-trend traders to close, producing sharp directional bursts.",
        "best_market_conditions": ["Emerging breakouts from multi-hour consolidation", "Surging volume with expanding candle bodies"],
        "unfavorable_conditions": ["Low liquidity, declining volume phases", "Exhaustion candles at higher-timeframe resistance/support levels"],
        "default_parameters": {"rsi_threshold_long": 55, "rsi_threshold_short": 45, "volume_multiplier": 1.5, "atr_multiplier": 1.2, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-03",
        "strategy_number": "03",
        "name": "Daily Trend, 1H Trigger",
        "part": "PART I — TREND & CONTINUATION",
        "category": "Trend & Continuation",
        "primary_timeframe": "1D / 1H",
        "alternate_timeframes": ["4H / 15m"],
        "market": "BTC / ETH / Major liquid alts",
        "direction": "LONG / SHORT",
        "complexity": "Intermediate",
        "status": "APPROVED",
        "compatible_regimes": ["TRENDING"],
        "data_requirements": ["Daily OHLCV", "1H OHLCV", "Daily EMA (50, 200)", "1H EMA (20)", "1H RSI (14)"],
        "what_it_does": "Uses the Daily timeframe to establish macro directional trend bias and executes high-precision entries on the 1-hour chart using intraday structure breaks.",
        "why_it_exists": "Aligning lower-timeframe tactical execution with higher-timeframe order flow reduces whipsaws and maximizes risk-to-reward ratio.",
        "best_market_conditions": ["Clear Daily trend with clean structural alignment", "Daily EMA 50 > EMA 200 with widening spread"],
        "unfavorable_conditions": ["Conflicted multi-timeframe bias (Daily flat, 1H choppy)", "Daily chart inside multi-week consolidation box"],
        "default_parameters": {"daily_ema_fast": 50, "daily_ema_slow": 200, "hourly_ema_trigger": 20, "rsi_pullback_level": 40, "rr_ratio": 2.5},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-04",
        "strategy_number": "04",
        "name": "Trend Resumption After Squeeze",
        "part": "PART I — TREND & CONTINUATION",
        "category": "Trend & Continuation",
        "primary_timeframe": "4H",
        "alternate_timeframes": ["1H", "1D"],
        "market": "BTC / ETH / Mid-cap alts",
        "direction": "LONG / SHORT",
        "complexity": "Intermediate",
        "status": "APPROVED",
        "compatible_regimes": ["TRENDING", "LOW VOLATILITY"],
        "data_requirements": ["OHLCV", "Bollinger Bands (20, 2.0)", "Keltner Channel (20, 1.5 ATR)", "EMA (50)", "Momentum (12)"],
        "what_it_does": "Monitors existing trends that enter low-volatility compression (Bollinger Bands inside Keltner Channels), entering upon volatility release in the direction of the dominant trend.",
        "why_it_exists": "Volatility is cyclical. Compressions store energy; when the squeeze releases, trend resumption occurs with high directional velocity.",
        "best_market_conditions": ["Defined higher-timeframe trend experiencing temporary volume drying/consolidation"],
        "unfavorable_conditions": ["Squeeze firing against higher-timeframe 200 EMA slope", "Declining overall market volume across universe"],
        "default_parameters": {"bb_period": 20, "bb_std": 2.0, "kc_period": 20, "kc_atr_mult": 1.5, "min_squeeze_bars": 3, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-05",
        "strategy_number": "05",
        "name": "Time-Series Momentum",
        "part": "PART I — TREND & CONTINUATION",
        "category": "Trend & Continuation",
        "primary_timeframe": "1D / 4H",
        "alternate_timeframes": ["1W", "1D"],
        "market": "BTC / ETH / Top 20 liquid alts",
        "direction": "LONG / SHORT",
        "complexity": "Institutional",
        "status": "APPROVED",
        "compatible_regimes": ["TRENDING"],
        "data_requirements": ["Daily OHLCV", "30D/60D/90D Historical Returns", "20D Realized Volatility", "ATR (20)"],
        "what_it_does": "Measures quantitative momentum across 30, 60, and 90-day lookback horizons, allocating long exposure to assets exhibiting positive cumulative returns and filtering out deteriorating momentum.",
        "why_it_exists": "Capital allocation flows persistently toward outperforming crypto assets over multi-week horizons due to fund rebalancing and institutional liquidity cycles.",
        "best_market_conditions": ["Macro bull or bear trend regimes", "Persistent dispersion between leading and lagging crypto assets"],
        "unfavorable_conditions": ["Widespread market consolidation with high volatility churn", "Liquidation cascade shocks across all pairs simultaneously"],
        "default_parameters": {"lookback_short": 30, "lookback_long": 90, "vol_lookback": 20, "max_vol_percentile": 80, "rr_ratio": 2.0},
        "version": "1.0.0"
    },

    # PART II — BREAKOUT & EXPANSION
    {
        "strategy_id": "crypto-strat-06",
        "strategy_number": "06",
        "name": "BandWidth Squeeze Breakout",
        "part": "PART II — BREAKOUT & EXPANSION",
        "category": "Breakout & Expansion",
        "primary_timeframe": "4H / 1D",
        "alternate_timeframes": ["1H", "4H"],
        "market": "BTC / ETH / High Beta Alts",
        "direction": "LONG / SHORT",
        "complexity": "Intermediate",
        "status": "APPROVED",
        "compatible_regimes": ["BREAKOUT / EXPANSION", "LOW VOLATILITY"],
        "data_requirements": ["OHLCV", "Bollinger Bands (20, 2.0)", "BandWidth 100-bar Percentile", "Volume SMA (20)"],
        "what_it_does": "Calculates normalized Bollinger BandWidth. When BandWidth falls into historical extreme compression (lowest 15th percentile), the strategy primes and enters as price breaks outside the outer band on expanding volume.",
        "why_it_exists": "Extreme volatility compression indicates an impending imbalance between buyers and sellers. When price breaks out of the range, resting liquidity is triggered, fueling follow-through.",
        "best_market_conditions": ["Extended multi-day low-volatility sideways ranges", "BandWidth <= 15th percentile of past 100 bars"],
        "unfavorable_conditions": ["Choppy ranges with expanding BandWidth", "Breakout candle with low volume / long opposing wick"],
        "default_parameters": {"bb_period": 20, "bb_std": 2.0, "bw_percentile_threshold": 15, "vol_multiplier": 2.0, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-07",
        "strategy_number": "07",
        "name": "Donchian 20 Breakout",
        "part": "PART II — BREAKOUT & EXPANSION",
        "category": "Breakout & Expansion",
        "primary_timeframe": "1D / 4H",
        "alternate_timeframes": ["4H", "1D"],
        "market": "BTC / ETH / Major Liquid Alts",
        "direction": "LONG / SHORT",
        "complexity": "Introductory",
        "status": "APPROVED",
        "compatible_regimes": ["BREAKOUT / EXPANSION", "TRENDING"],
        "data_requirements": ["OHLCV", "Donchian Channel (20-period)", "Donchian Exit Channel (10-period)", "ATR (20)"],
        "what_it_does": "Classic quantitative trend-following breakout. Enters when price makes a new 20-period highest high (Long) or lowest low (Short), with trailing stop governed by the 10-period opposing channel.",
        "why_it_exists": "Captures thick-tailed trend distributions in crypto by remaining in positions as long as new periodic extremes continue to form.",
        "best_market_conditions": ["Strong secular trending crypto bull or bear runs", "Sustained directional impulse waves"],
        "unfavorable_conditions": ["Mean-reverting tight ranges where price repeatedly tags upper and lower Donchian bounds"],
        "default_parameters": {"entry_period": 20, "exit_period": 10, "atr_period": 20, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-08",
        "strategy_number": "08",
        "name": "UTC Opening Range Breakout",
        "part": "PART II — BREAKOUT & EXPANSION",
        "category": "Breakout & Expansion",
        "primary_timeframe": "15m / 1H",
        "alternate_timeframes": ["5m", "15m"],
        "market": "BTC / ETH",
        "direction": "LONG / SHORT",
        "complexity": "Intermediate",
        "status": "APPROVED",
        "compatible_regimes": ["BREAKOUT / EXPANSION"],
        "data_requirements": ["15m OHLCV", "00:00-01:00 UTC Opening Range High/Low", "Daily VWAP", "ATR (14)"],
        "what_it_does": "Defines the price range established during the first hour of the UTC day (00:00 to 01:00 UTC). Enters on a high-volume 15-minute candle breakout outside this opening range in the direction of Daily VWAP.",
        "why_it_exists": "UTC 00:00 marks the daily candle open, funding settlement, and derivative reset across major global exchanges, frequently setting the directional tone for the subsequent 24 hours.",
        "best_market_conditions": ["Days with clear early institutional participation following UTC open", "Tight 00:00-01:00 UTC range (< 1.0% width)"],
        "unfavorable_conditions": ["Wide opening range (> 2.5% width on BTC)", "Price immediately reversing back into the opening range on weak volume"],
        "default_parameters": {"start_hour_utc": 0, "range_duration_hours": 1, "max_range_width_pct": 1.5, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-09",
        "strategy_number": "09",
        "name": "Previous-Day High/Low Break",
        "part": "PART II — BREAKOUT & EXPANSION",
        "category": "Breakout & Expansion",
        "primary_timeframe": "1H / 4H",
        "alternate_timeframes": ["15m", "1H"],
        "market": "BTC / ETH / Major Alts",
        "direction": "LONG / SHORT",
        "complexity": "Intermediate",
        "status": "APPROVED",
        "compatible_regimes": ["BREAKOUT / EXPANSION", "TRENDING"],
        "data_requirements": ["Previous Day High (PDH)", "Previous Day Low (PDL)", "Previous Day Close (PDC)", "Volume SMA (20)", "1H OHLCV"],
        "what_it_does": "Tracks Previous Day High (PDH) and Previous Day Low (PDL) as primary liquidity milestones. Enters when an hourly candle breaks and closes beyond PDH/PDL with relative volume expansion and no immediate rejection.",
        "why_it_exists": "Stops and breakout orders heavily cluster at prior daily extremes. A clean acceptance beyond these levels triggers sustained continuation.",
        "best_market_conditions": ["Trending days breaking prior day ranges in the direction of the dominant weekly trend", "Relative volume > 1.4x at the point of breakout"],
        "unfavorable_conditions": ["Range-bound consolidation days where PDH/PDL are simply probed and rejected (liquidity sweeps)"],
        "default_parameters": {"rvol_threshold": 1.4, "bar_close_threshold_pct": 30, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-10",
        "strategy_number": "10",
        "name": "Breakout Retest",
        "part": "PART II — BREAKOUT & EXPANSION",
        "category": "Breakout & Expansion",
        "primary_timeframe": "1H / 4H",
        "alternate_timeframes": ["15m", "1H"],
        "market": "BTC / ETH / Liquid Alts",
        "direction": "LONG / SHORT",
        "complexity": "Intermediate",
        "status": "APPROVED",
        "compatible_regimes": ["BREAKOUT / EXPANSION", "TRENDING"],
        "data_requirements": ["OHLCV", "Key Horizontal Level Detector", "EMA (20)", "Volume SMA (20)", "ATR (14)"],
        "what_it_does": "After price breaks out of a major horizontal support or resistance level, this strategy waits for an orderly retest back to the broken level, entering only when a rejection candle confirms the level has flipped from resistance to support (or vice-versa).",
        "why_it_exists": "Allows entering high-probability breakout moves with significantly reduced slippage and tighter stop loss placement compared to chasing initial impulse bars.",
        "best_market_conditions": ["Clean breakouts followed by low-volume shallow pullbacks to the breakout boundary", "Strong rejection wicks off the retested level"],
        "unfavorable_conditions": ["Violent retests that slice cleanly back inside the prior range (failed breakout)", "High-volume selling into retest support"],
        "default_parameters": {"retest_tolerance_pct": 0.3, "max_retest_volume_ratio": 1.0, "rr_ratio": 2.0},
        "version": "1.0.0"
    },

    # PART III — PULLBACK & MEAN REVERSION
    {
        "strategy_id": "crypto-strat-11",
        "strategy_number": "11",
        "name": "Bollinger Reversion",
        "part": "PART III — PULLBACK & MEAN REVERSION",
        "category": "Pullback & Mean Reversion",
        "primary_timeframe": "1H / 4H",
        "alternate_timeframes": ["15m", "1H"],
        "market": "BTC / ETH / Range-bound Alts",
        "direction": "LONG / SHORT",
        "complexity": "Intermediate",
        "status": "APPROVED",
        "compatible_regimes": ["RANGING"],
        "data_requirements": ["OHLCV", "Bollinger Bands (20, 2.5 std)", "ADX (14)", "RSI (14)"],
        "what_it_does": "Evaluates ranging market conditions (ADX < 20). When price extends to touch or pierce the 2.5 standard deviation Bollinger Band with extreme RSI, the strategy fades the extension and targets a return to the 20-period middle moving average.",
        "why_it_exists": "In non-trending, range-bound environments, price extensions beyond 2.5 standard deviations are statistically unsustainable and revert rapidly to the mean.",
        "best_market_conditions": ["Confirmed range-bound markets with ADX < 20 and flat 50 EMA", "Clean rejection wicks off the outer 2.5 standard deviation band"],
        "unfavorable_conditions": ["Strong trending regimes (ADX > 25) where price 'walks the bands' causing deep drawdowns on counter-trend fades"],
        "default_parameters": {"bb_period": 20, "bb_std": 2.5, "max_adx": 20, "rsi_oversold": 30, "rsi_overbought": 70},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-12",
        "strategy_number": "12",
        "name": "RSI Extreme Reversion",
        "part": "PART III — PULLBACK & MEAN REVERSION",
        "category": "Pullback & Mean Reversion",
        "primary_timeframe": "15m / 1H",
        "alternate_timeframes": ["5m", "15m", "4H"],
        "market": "BTC / ETH / Alts",
        "direction": "LONG / SHORT",
        "complexity": "Introductory",
        "status": "APPROVED",
        "compatible_regimes": ["RANGING", "HIGH VOLATILITY"],
        "data_requirements": ["OHLCV", "RSI (14)", "EMA (200)", "ATR (14)"],
        "what_it_does": "Flags extreme momentum exhaustion when 14-period RSI reaches rare historical tails (<= 20 or >= 80). Enters when price forms a reversal candle closing back above 25 / below 75, aiming for a retest of intermediate moving averages.",
        "why_it_exists": "Rapid panic liquidations or euphoric spikes exhaust available market orders, creating brief vacuum periods where prices snap back quickly.",
        "best_market_conditions": ["Exhaustion flushes within larger trading ranges", "Sharp counter-trend spikes that immediately run out of volume"],
        "unfavorable_conditions": ["Runaway fundamental trend breakdowns where RSI stays pinned <= 15 for days"],
        "default_parameters": {"rsi_period": 14, "extreme_low": 20, "extreme_high": 80, "exit_rsi_low": 25, "exit_rsi_high": 75, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-13",
        "strategy_number": "13",
        "name": "Anchored VWAP Reversion",
        "part": "PART III — PULLBACK & MEAN REVERSION",
        "category": "Pullback & Mean Reversion",
        "primary_timeframe": "1H / 4H",
        "alternate_timeframes": ["15m", "1H"],
        "market": "BTC / ETH / Major Liquid Alts",
        "direction": "LONG / SHORT",
        "complexity": "Advanced",
        "status": "APPROVED",
        "compatible_regimes": ["RANGING", "HIGH VOLATILITY"],
        "data_requirements": ["OHLCV", "Anchored VWAP from Key Pivot", "VWAP Std Dev Bands (+/- 2.0 std)", "Volume"],
        "what_it_does": "Calculates volume-weighted average price anchored to significant structural swing points (monthly open, weekly high/low, or major liquidation events). Enters mean-reversion trades when price reaches outer standard deviation bands (+/- 2.0 std) and shows exhaustion.",
        "why_it_exists": "Anchored VWAP represents the true volume-weighted cost basis of participants since the anchor event. Large deviations from this baseline incentivize mean-reverting liquidity providers.",
        "best_market_conditions": ["Markets extended beyond 2 standard deviations from major structural event anchors", "Declining volume as price probes outer deviation bands"],
        "unfavorable_conditions": ["Price initiating a fresh fundamental breakout wave with high sustained institutional volume"],
        "default_parameters": {"anchor_type": "MONTHLY_OPEN", "std_multiplier": 2.0, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-14",
        "strategy_number": "14",
        "name": "ATR Extension Reversal",
        "part": "PART III — PULLBACK & MEAN REVERSION",
        "category": "Pullback & Mean Reversion",
        "primary_timeframe": "1H / 4H",
        "alternate_timeframes": ["15m", "1H"],
        "market": "BTC / ETH / Volatile Alts",
        "direction": "LONG / SHORT",
        "complexity": "Intermediate",
        "status": "APPROVED",
        "compatible_regimes": ["HIGH VOLATILITY", "RANGING"],
        "data_requirements": ["OHLCV", "20-period Moving Average", "ATR (14)", "ATR Multiplier Envelope (3.0x)"],
        "what_it_does": "Calculates the absolute distance between price and its 20-period baseline in multiples of ATR. When distance exceeds 3.0x ATR 14 without structural support, the strategy enters a mean reversion fade back toward the 20 MA.",
        "why_it_exists": "Price rarely travels beyond 3.0x ATR away from its baseline without pausing or pulling back to digest the move.",
        "best_market_conditions": ["Overextended emotional rallies or capitulation sell-offs in volatile altcoins"],
        "unfavorable_conditions": ["Strong trend breakouts with high continuous volume and macro catalysts"],
        "default_parameters": {"ma_period": 20, "atr_period": 14, "extension_multiplier": 3.0, "min_wick_pct": 40, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-15",
        "strategy_number": "15",
        "name": "Range Fade",
        "part": "PART III — PULLBACK & MEAN REVERSION",
        "category": "Pullback & Mean Reversion",
        "primary_timeframe": "1H / 4H",
        "alternate_timeframes": ["15m", "1H"],
        "market": "BTC / ETH / Established Range Alts",
        "direction": "LONG / SHORT",
        "complexity": "Introductory",
        "status": "APPROVED",
        "compatible_regimes": ["RANGING"],
        "data_requirements": ["OHLCV", "Range High (RH)", "Range Low (RL)", "Range Midpoint (EQ)", "ADX (14)"],
        "what_it_does": "Identifies validated horizontal trading ranges with at least 2 touches per boundary. Enters fade orders when price tests the boundary, fails to expand, and closes back inside the range, targeting the Range Equilibrium (EQ).",
        "why_it_exists": "Range boundaries act as institutional supply and demand walls until structural balance shifts.",
        "best_market_conditions": ["Consolidated market conditions with flat ADX < 18", "Multiple confirmed touches of horizontal support and resistance"],
        "unfavorable_conditions": ["Approaching macro breakout catalysts, high volume expansion candles breaking range boundaries"],
        "default_parameters": {"min_range_touches": 2, "max_adx": 18, "target_at_eq": True, "rr_ratio": 2.0},
        "version": "1.0.0"
    },

    # PART IV — STRUCTURE & REVERSAL
    {
        "strategy_id": "crypto-strat-16",
        "strategy_number": "16",
        "name": "Swing Sweep Reversal",
        "part": "PART IV — STRUCTURE & REVERSAL",
        "category": "Structure & Reversal",
        "primary_timeframe": "15m / 1H",
        "alternate_timeframes": ["5m", "15m", "4H"],
        "market": "BTC / ETH / Liquid Alts",
        "direction": "LONG / SHORT",
        "complexity": "Advanced",
        "status": "APPROVED",
        "compatible_regimes": ["STRUCTURAL REVERSAL", "RANGING"],
        "data_requirements": ["OHLCV", "Swing High / Low Liquidity Pools", "Fair Value Gap (FVG)", "Volume Delta"],
        "what_it_does": "Detects stop-runs and liquidity sweeps. When price pierces a key swing high/low to take resting liquidity but immediately reverses and closes back inside the prior range with a long wick, the strategy enters in the reversal direction.",
        "why_it_exists": "Market makers and institutional algos frequently push price beyond obvious swing highs/lows to trigger resting buy/sell stops, capturing counterparty liquidity before moving price the opposite way.",
        "best_market_conditions": ["Clear swing highs and lows with heavy clustered liquidity", "Immediate wick rejection within 1-2 candles of the sweep"],
        "unfavorable_conditions": ["True structural breakout where price sweeps and accelerates with expanding delta volume"],
        "default_parameters": {"swing_period": 20, "min_wick_ratio_pct": 50, "max_sweep_bars": 2, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-17",
        "strategy_number": "17",
        "name": "Failed Breakout Reversal",
        "part": "PART IV — STRUCTURE & REVERSAL",
        "category": "Structure & Reversal",
        "primary_timeframe": "1H / 4H",
        "alternate_timeframes": ["15m", "1H"],
        "market": "BTC / ETH / Alts",
        "direction": "LONG / SHORT",
        "complexity": "Intermediate",
        "status": "APPROVED",
        "compatible_regimes": ["STRUCTURAL REVERSAL", "RANGING"],
        "data_requirements": ["OHLCV", "Key Support / Resistance", "Volume Delta Imbalance", "2-bar Reversal Pattern"],
        "what_it_does": "When a breakout bar breaches a major support or resistance level but the very next candle fails to follow through and engulfs back inside the level, the strategy enters a reversal trade targeting the opposing range boundary.",
        "why_it_exists": "Trapped breakout traders who entered late are forced to market-sell/buy to exit, providing intense fuel for an aggressive counter-reversal.",
        "best_market_conditions": ["Range-bound markets creating deceptive breakout attempts", "Bearish/Bullish engulfing candle immediately following breakout candle"],
        "unfavorable_conditions": ["High sustained volume trends with genuine multi-timeframe breakout momentum"],
        "default_parameters": {"require_engulfing": True, "min_volume_ratio": 1.0, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-18",
        "strategy_number": "18",
        "name": "Prior-Level Rejection",
        "part": "PART IV — STRUCTURE & REVERSAL",
        "category": "Structure & Reversal",
        "primary_timeframe": "1H / 4H",
        "alternate_timeframes": ["15m", "1H"],
        "market": "BTC / ETH / Major Alts",
        "direction": "LONG / SHORT",
        "complexity": "Introductory",
        "status": "APPROVED",
        "compatible_regimes": ["RANGING", "STRUCTURAL REVERSAL"],
        "data_requirements": ["Prior Week High / Low (PWH/PWL)", "Prior Month High / Low (PMH/PML)", "Rejection Wick Ratio", "OHLCV"],
        "what_it_does": "Monitors multi-period macro benchmark levels (Prior Week High/Low, Prior Month High/Low). Enters sharp reversal trades when price tests these levels and prints a clear rejection pin bar.",
        "why_it_exists": "Weekly and monthly highs and lows represent major institutional macro boundaries where substantial rebalancing orders reside.",
        "best_market_conditions": ["Clean tests of prior weekly or monthly extremes in non-trending or mature trend phases"],
        "unfavorable_conditions": ["Fresh secular breakout impulse bars with no wick rejection"],
        "default_parameters": {"level_tolerance_pct": 0.2, "min_wick_pct": 55, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-19",
        "strategy_number": "19",
        "name": "Structure Break + Retest",
        "part": "PART IV — STRUCTURE & REVERSAL",
        "category": "Structure & Reversal",
        "primary_timeframe": "1H / 4H / 1D",
        "alternate_timeframes": ["15m", "1H"],
        "market": "BTC / ETH / Liquid Alts",
        "direction": "LONG / SHORT",
        "complexity": "Intermediate",
        "status": "APPROVED",
        "compatible_regimes": ["STRUCTURAL REVERSAL"],
        "data_requirements": ["OHLCV", "Market Structure Highs/Lows (MSB / CHoCH)", "Order Block (OB)", "ATR (14)"],
        "what_it_does": "Detects structural market trend shifts (Change of Character / MSB) where an ongoing sequence of Higher Highs is broken by a displacement candle closing below the prior Higher Low. Waits for a retest of the origin Order Block before executing.",
        "why_it_exists": "Signals that institutional inventory has rotated from accumulation to distribution (or vice versa), establishing the first leg of a new structural trend.",
        "best_market_conditions": ["Clear exhaustion of prior multi-day trend followed by sharp structural displacement"],
        "unfavorable_conditions": ["Choppy sideways environments with no defined higher highs or lower lows"],
        "default_parameters": {"min_displacement_atr": 1.0, "ob_zone_depth_pct": 50, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-20",
        "strategy_number": "20",
        "name": "Daily Compression Expansion",
        "part": "PART IV — STRUCTURE & REVERSAL",
        "category": "Structure & Reversal",
        "primary_timeframe": "1D / 4H",
        "alternate_timeframes": ["4H", "1D"],
        "market": "BTC / ETH / Alts",
        "direction": "LONG / SHORT",
        "complexity": "Intermediate",
        "status": "APPROVED",
        "compatible_regimes": ["LOW VOLATILITY", "BREAKOUT / EXPANSION"],
        "data_requirements": ["Daily OHLCV", "NR7 Indicator (Narrowest Range of 7 days)", "Daily ATR (14)"],
        "what_it_does": "Identifies Inside Days and NR7 patterns (a daily candle whose high-low range is the narrowest of the past 7 days). Enters a breakout trade on the next day's open when price breaches the NR7 high or low.",
        "why_it_exists": "Markets continually oscillate between contraction and expansion. NR7 represents maximum volatility contraction, which is statistically followed by high-volatility expansion.",
        "best_market_conditions": ["Mature consolidation phases with 7 consecutive days of declining range width"],
        "unfavorable_conditions": ["High volatility choppy market environments with expanding daily candle ranges"],
        "default_parameters": {"nr_lookback": 7, "require_inside_bar": True, "rr_ratio": 2.0},
        "version": "1.0.0"
    },

    # PART V — MOMENTUM & VOLUME
    {
        "strategy_id": "crypto-strat-21",
        "strategy_number": "21",
        "name": "Relative Volume Breakout",
        "part": "PART V — MOMENTUM & VOLUME",
        "category": "Momentum & Volume",
        "primary_timeframe": "15m / 1H",
        "alternate_timeframes": ["5m", "15m", "4H"],
        "market": "BTC / ETH / High Volume Alts",
        "direction": "LONG / SHORT",
        "complexity": "Intermediate",
        "status": "APPROVED",
        "compatible_regimes": ["BREAKOUT / EXPANSION"],
        "data_requirements": ["OHLCV", "RVOL (Relative Volume vs Time of Day)", "EMA (20)", "ATR (14)"],
        "what_it_does": "Calculates Relative Volume (RVOL) against normalized time-of-day volume profiles. Enters when price breaks out of a multi-hour consolidation while RVOL surges >= 2.5x standard volume, indicating institutional participation.",
        "why_it_exists": "Breakouts accompanied by high relative volume have statistically lower failure rates because institutional capital commitment is present.",
        "best_market_conditions": ["Consolidations resolving with sudden aggressive volume spikes", "High-liquidity market trading sessions"],
        "unfavorable_conditions": ["Low liquidity hours with artificial low-volume drift"],
        "default_parameters": {"min_rvol": 2.5, "min_body_pct": 70, "consolidation_bars": 10, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-22",
        "strategy_number": "22",
        "name": "Volume Dry-Up Continuation",
        "part": "PART V — MOMENTUM & VOLUME",
        "category": "Momentum & Volume",
        "primary_timeframe": "1H / 4H",
        "alternate_timeframes": ["15m", "1H"],
        "market": "BTC / ETH / Trending Alts",
        "direction": "LONG / SHORT",
        "complexity": "Intermediate",
        "status": "APPROVED",
        "compatible_regimes": ["TRENDING"],
        "data_requirements": ["OHLCV", "Volume SMA (20)", "EMA (20, 50)", "ATR (14)"],
        "what_it_does": "In an established trend, after a strong impulse wave on heavy volume, price enters a shallow pullback where volume dries up to < 50% of the 20-period average. Enters as volume re-expands in the trend direction.",
        "why_it_exists": "Volume dry-up during a pullback proves that counter-trend selling is weak and lacks institutional backing, signaling high likelihood of trend resumption.",
        "best_market_conditions": ["Healthy trending markets with orderly, low-volume pullbacks to the 20 EMA"],
        "unfavorable_conditions": ["High volume pullbacks indicating aggressive institutional distribution"],
        "default_parameters": {"max_dry_up_vol_ratio": 0.5, "min_trigger_vol_ratio": 1.2, "ema_fast": 20, "ema_slow": 50, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-23",
        "strategy_number": "23",
        "name": "Volume Climax Reversal",
        "part": "PART V — MOMENTUM & VOLUME",
        "category": "Momentum & Volume",
        "primary_timeframe": "15m / 1H",
        "alternate_timeframes": ["5m", "15m"],
        "market": "BTC / ETH / High Beta Alts",
        "direction": "LONG / SHORT",
        "complexity": "Advanced",
        "status": "APPROVED",
        "compatible_regimes": ["HIGH VOLATILITY", "STRUCTURAL REVERSAL"],
        "data_requirements": ["OHLCV", "Volume Z-Score (> 3.5 std)", "RSI (14)", "ATR (14)"],
        "what_it_does": "Detects blow-off tops or capitulation selling climaxes characterized by parabolic price extension and extreme volume Z-scores (> 3.5 standard deviations above 50-period mean). Enters a counter-trend fade when an exhaustion candle prints.",
        "why_it_exists": "Parabolic volume climaxes indicate the total exhaustion of aggressive market orders (the 'last buyers' or 'last sellers' market-entering), leaving the book wide open for an immediate sharp reversal.",
        "best_market_conditions": ["Sudden emotional liquidation cascades or parabolic pump-and-dump spikes"],
        "unfavorable_conditions": ["Early stages of fresh fundamental news cycles with unlimited spot demand"],
        "default_parameters": {"min_volume_z_score": 3.5, "rsi_climax_low": 15, "rsi_climax_high": 85, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-24",
        "strategy_number": "24",
        "name": "OBV Divergence",
        "part": "PART V — MOMENTUM & VOLUME",
        "category": "Momentum & Volume",
        "primary_timeframe": "1H / 4H",
        "alternate_timeframes": ["15m", "1H"],
        "market": "BTC / ETH / Major Alts",
        "direction": "LONG / SHORT",
        "complexity": "Intermediate",
        "status": "APPROVED",
        "compatible_regimes": ["STRUCTURAL REVERSAL", "RANGING"],
        "data_requirements": ["OHLCV", "On-Balance Volume (OBV)", "OBV 20-period EMA", "Price Swing Highs/Lows"],
        "what_it_does": "Detects divergences between price swings and cumulative On-Balance Volume. When price prints a Lower Low but OBV prints a Higher Low (Bullish Divergence) or price prints a Higher High while OBV prints a Lower High (Bearish Divergence), enters upon OBV crossing its 20 EMA.",
        "why_it_exists": "OBV aggregates buying and selling volume. A divergence reveals underlying institutional accumulation or distribution occurring silently beneath deceptive price action.",
        "best_market_conditions": ["Mature trends approaching key macro support or resistance levels", "Multi-day divergences across 1H and 4H timeframes"],
        "unfavorable_conditions": ["Early stage high-momentum breakout trends where price and OBV expand in lockstep"],
        "default_parameters": {"obv_ema_period": 20, "swing_lookback": 10, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-25",
        "strategy_number": "25",
        "name": "VWAP Reclaim on Volume",
        "part": "PART V — MOMENTUM & VOLUME",
        "category": "Momentum & Volume",
        "primary_timeframe": "15m / 1H",
        "alternate_timeframes": ["5m", "15m"],
        "market": "BTC / ETH / Liquid Alts",
        "direction": "LONG / SHORT",
        "complexity": "Introductory",
        "status": "APPROVED",
        "compatible_regimes": ["TRENDING", "BREAKOUT / EXPANSION"],
        "data_requirements": ["OHLCV", "Session VWAP", "Volume SMA (20)", "EMA (5)"],
        "what_it_does": "When price temporarily dips below the daily session VWAP in an intraday trend, this strategy waits for buyers to aggressively step in and reclaim VWAP with a high-volume candle closing cleanly above the VWAP line.",
        "why_it_exists": "Institutional execution algos use VWAP as their benchmark execution price. An aggressive reclaim on above-average volume demonstrates institutional willingness to pay up above the daily average price.",
        "best_market_conditions": ["Intraday trending days where VWAP is sloping upward (Long) or downward (Short)", "Reclaim candle volume > 1.5x 20-period average"],
        "unfavorable_conditions": ["Flat, horizontal VWAP regimes with price oscillating back and forth across the line"],
        "default_parameters": {"min_dip_bars": 2, "min_volume_multiplier": 1.5, "bar_close_top_pct": 30, "rr_ratio": 2.0},
        "version": "1.0.0"
    },

    # PART VI — CRYPTO-SPECIFIC & MULTI-FACTOR
    {
        "strategy_id": "crypto-strat-26",
        "strategy_number": "26",
        "name": "Basis Extreme Reversal",
        "part": "PART VI — CRYPTO-SPECIFIC & MULTI-FACTOR",
        "category": "Crypto-Specific & Multi-Factor",
        "primary_timeframe": "1H / 4H",
        "alternate_timeframes": ["15m", "1H"],
        "market": "BTC / ETH Futures vs Spot Basis",
        "direction": "LONG / SHORT",
        "complexity": "Institutional",
        "status": "APPROVED",
        "compatible_regimes": ["STRUCTURAL REVERSAL", "HIGH VOLATILITY"],
        "data_requirements": ["Spot Index Price", "Perpetual / Quarterly Futures Price", "Annualized Basis Spread", "30-Day Historical Basis Mean & Std"],
        "what_it_does": "Tracks the annualized basis spread between Spot and Perpetual/Futures prices. When basis deviates >= 2.5 standard deviations from its 30-day mean (indicating extreme overleveraged contango or panic backwardation), the strategy enters a basis compression reversal trade.",
        "why_it_exists": "Perpetual funding rate mechanics and futures basis arbitrage force extreme basis dislocations to compress back toward equilibrium as arbitrageurs deploy capital.",
        "best_market_conditions": ["Periods of extreme euphoria (annualized basis > 35%) or capitulation discount (negative basis / backwardation)"],
        "unfavorable_conditions": ["Quiet, neutral basis environments (basis within +/- 0.5 std of historical mean)"],
        "default_parameters": {"basis_z_score_threshold": 2.5, "lookback_days": 30, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-27",
        "strategy_number": "27",
        "name": "Open Interest Expansion",
        "part": "PART VI — CRYPTO-SPECIFIC & MULTI-FACTOR",
        "category": "Crypto-Specific & Multi-Factor",
        "primary_timeframe": "1H / 4H",
        "alternate_timeframes": ["15m", "1H"],
        "market": "BTC / ETH / Derivatives",
        "direction": "LONG / SHORT",
        "complexity": "Institutional",
        "status": "APPROVED",
        "compatible_regimes": ["BREAKOUT / EXPANSION", "TRENDING"],
        "data_requirements": ["Aggregated Open Interest (OI)", "Price OHLCV", "Funding Rate", "OI 4-Hour Delta (%)"],
        "what_it_does": "Monitors real-time aggregated derivative Open Interest. When OI expands rapidly by >= 8% in 4 hours while price breaks out of consolidation with stable/neutral funding, the strategy enters in the breakout direction, confirming that new capital is actively fueling the move.",
        "why_it_exists": "Distinguishes genuine institutional expansion from weak short-covering rallies. True breakouts are characterized by rising price AND surging Open Interest.",
        "best_market_conditions": ["Consolidations resolving with explosive Open Interest expansion and low/moderate funding rates"],
        "unfavorable_conditions": ["Price rallies accompanied by declining Open Interest (pure short-covering that exhausts quickly)", "Extremely overheated funding rates (> 0.05% per 8h)"],
        "default_parameters": {"min_oi_delta_pct": 8.0, "oi_lookback_hours": 4, "max_funding_rate_pct": 0.04, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-28",
        "strategy_number": "28",
        "name": "Flush & Reclaim",
        "part": "PART VI — CRYPTO-SPECIFIC & MULTI-FACTOR",
        "category": "Crypto-Specific & Multi-Factor",
        "primary_timeframe": "15m / 1H",
        "alternate_timeframes": ["5m", "15m"],
        "market": "BTC / ETH / High Leverage Derivatives",
        "direction": "LONG / SHORT",
        "complexity": "Advanced",
        "status": "APPROVED",
        "compatible_regimes": ["STRUCTURAL REVERSAL", "HIGH VOLATILITY"],
        "data_requirements": ["Liquidations Feed / Sudden OI Drop", "Session VWAP", "Tick Delta Imbalance", "15m OHLCV"],
        "what_it_does": "Captures violent liquidation cascades. When price experiences a sudden flush triggering heavy liquidations and an immediate drop in Open Interest, and then aggressively reclaims the pre-flush level within 2 bars, the strategy enters long, riding the sharp V-reversal.",
        "why_it_exists": "Liquidation flushes clean out overleveraged retail positions. Once the liquidation cascade clears, market makers and institutional buyers step into the order vacuum to bid price back to fair value.",
        "best_market_conditions": ["High leverage liquidation events where price spikes downward, cleans the order book, and immediately V-bounces"],
        "unfavorable_conditions": ["True catastrophic macro liquidation events with sustained selling and broken spot markets"],
        "default_parameters": {"min_flush_pct": 2.5, "max_reclaim_bars": 2, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-29",
        "strategy_number": "29",
        "name": "Dominance-Filtered Alt Trend",
        "part": "PART VI — CRYPTO-SPECIFIC & MULTI-FACTOR",
        "category": "Crypto-Specific & Multi-Factor",
        "primary_timeframe": "4H / 1D",
        "alternate_timeframes": ["1H", "4H"],
        "market": "Altcoins filtered by BTC Dominance (BTC.D)",
        "direction": "LONG / SHORT",
        "complexity": "Advanced",
        "status": "APPROVED",
        "compatible_regimes": ["TRENDING"],
        "data_requirements": ["BTC Dominance Index (BTC.D)", "BTC/USDT Trend", "Altcoin OHLCV", "EMA (20, 50)"],
        "what_it_does": "Filters altcoin long setups using macro Bitcoin Dominance (BTC.D). Altcoin trend breakouts are ONLY permitted when BTC.D is declining below its 50 EMA and BTC is stable/uptrending (Altseason regime). In rising BTC.D regimes, altcoin longs are blocked.",
        "why_it_exists": "Altcoins consistently underperform and suffer severe liquidity drains when Bitcoin Dominance is rising. Filtering altcoin exposure through BTC.D dramatically increases breakout follow-through.",
        "best_market_conditions": ["Declining BTC Dominance with BTC/USDT consolidating sideways or trending upward peacefully"],
        "unfavorable_conditions": ["Rising BTC Dominance (Bitcoin sucking liquidity out of altcoins)", "Sharp Bitcoin liquidation crashes (drags all alts down with higher beta)"],
        "default_parameters": {"btc_dominance_ema_period": 50, "btc_trend_ema_period": 50, "alt_volume_multiplier": 1.5, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
    {
        "strategy_id": "crypto-strat-30",
        "strategy_number": "30",
        "name": "Three-Factor Regime Setup",
        "part": "PART VI — CRYPTO-SPECIFIC & MULTI-FACTOR",
        "category": "Crypto-Specific & Multi-Factor",
        "primary_timeframe": "4H / 1D",
        "alternate_timeframes": ["1H", "4H"],
        "market": "BTC / ETH Multi-Asset",
        "direction": "LONG / SHORT",
        "complexity": "Institutional",
        "status": "APPROVED",
        "compatible_regimes": ["TRENDING", "BREAKOUT / EXPANSION"],
        "data_requirements": ["Factor 1: Trend Alignment (EMA 200/50)", "Factor 2: Volatility Regime (ATR/BandWidth percentile)", "Factor 3: Order Flow / OI & Funding", "Multi-Asset Feed"],
        "what_it_does": "Evaluates three independent quantitative market factors concurrently: (1) Macro Trend Alignment (EMA 50/200), (2) Volatility Expansion Envelope, and (3) Derivative Order Flow & Funding Health. Executes ONLY when all 3 macro factors produce unified unanimous confirmation.",
        "why_it_exists": "Single-indicator systems fail when regimes change. Requiring multi-factor mathematical confluence eliminates over 80% of false signals during ambiguous market phases.",
        "best_market_conditions": ["Major macro market transitions where trend, volatility, and order flow metrics align unanimously"],
        "unfavorable_conditions": ["Any market phase where any of the 3 quantitative factors disagrees or outputs conflicted data"],
        "default_parameters": {"ema_fast": 50, "ema_slow": 200, "max_funding_pct": 0.03, "require_unanimous": True, "rr_ratio": 2.0},
        "version": "1.0.0"
    },
]

def get_crypto_strategy_by_id(strategy_id: str) -> Dict[str, Any]:
    for strat in CRYPTO_30_STRATEGIES_BACKEND:
        if strat["strategy_id"] == strategy_id or strat["strategy_number"] == strategy_id:
            return strat
    return {}

def get_all_crypto_strategies() -> List[Dict[str, Any]]:
    return CRYPTO_30_STRATEGIES_BACKEND
